### ISSUE TITLE
Datatype sizes are too small for some models

### ISSUE THREAD

**Issue by bartteunis** [blender-to-gmstudio/blender-to-smf#10]
```python
struct.error: ubyte format requires 0 <= number <= 255
```
Throws an unhandled error when exporting: 
```python
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-to-smf\__init__.py", line 108, in execute
    return export_smf(self, self.filepath, context, self.export_textures, self.export_nla_tracks, self.export_type, self.mult, self.subdivisions)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-to-smf\smf.py", line 176, in export_smf
    rig_bytes.extend(pack('B',len(bones)))                      # nodeNum
struct.error: ubyte format requires 0 <= number <= 255

location: <unknown location>:-1
```

This is the case for the node number, the number of animations and the number of textures.

**Comment by bartteunis** [comment]
Example model: https://www.turbosquid.com/3d-models/3d-old-man-magician-fry-rigged-and-animated-1725126
